id: I1EEEE631
default_language: nl
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:53.780018
last_modified: 2023-01-04 11:32:53.780035
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  A348:
    title: The Prayer in Six Vajra Lines
    base_file: A348.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
